spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
     #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

  jpa:
     properties:
       hibernate:
         show_sql: true
         format_sql: true

#  mvc:
#    view:
#      prefix: /WEB-INF/view/
#      suffix: .jsp

  mvc:
    static-path-pattern: classpath:/**
#文件上传大小限制
#  servlet:
#    multipart:
#      max-file-size: 1024Mb
#      max-request-size: 2048Mb


#屏蔽日志
#logging:
#  level:
#    com.zy.*: 'off'
#更改项目端口和名称
server:
  port: 8080
  servlet:
    session:
      timeout: 1s
#  servlet:
#    context-path: /helloworld




